### ISSUE TITLE
Modular Chain: Error at startup

### ISSUE THREAD

**Issue by CyberAP** [MichaelPilyavskiy/ReaScript_Test#1]
How to reproduce:

- Create empty project
- Launch script
- Add ReaComp on track
- Get an error: mpl_ModularChain.lua:375: attempt to concatenate a nil value (local 'fx_guid').

**Comment by MichaelPilyavskiy** [comment]
Can`t reproduce. But I fixed potential bug. Make sure also you have Reaper5.20pre12a+ and SWS 2.8.3+

**Comment by CyberAP** [comment]
Fixed now. But nothing except moving FX blocks works. I suppose there should be wires from ins and outs?

**Comment by MichaelPilyavskiy** [comment]
Not yet. There is a lot of todo currently
